# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\PC-12\Desktop\EDDPOO_II.04.2023-IIE\SEMANA5\frmPago.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 335)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnProcesar = QtWidgets.QPushButton(self.centralwidget)
        self.btnProcesar.setGeometry(QtCore.QRect(360, 20, 120, 32))
        self.btnProcesar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"font: 75 18pt \"Agency FB\";")
        self.btnProcesar.setObjectName("btnProcesar")
        self.btnLimpiar = QtWidgets.QPushButton(self.centralwidget)
        self.btnLimpiar.setGeometry(QtCore.QRect(360, 70, 120, 32))
        self.btnLimpiar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"font: 75 18pt \"Agency FB\";")
        self.btnLimpiar.setObjectName("btnLimpiar")
        self.btnSalir = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalir.setGeometry(QtCore.QRect(360, 120, 120, 32))
        self.btnSalir.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"font: 75 18pt \"Agency FB\";")
        self.btnSalir.setObjectName("btnSalir")
        self.lblHoras = QtWidgets.QLabel(self.centralwidget)
        self.lblHoras.setGeometry(QtCore.QRect(20, 20, 90, 41))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblHoras.setFont(font)
        self.lblHoras.setStyleSheet("font: 13pt \"Gill Sans Ultra Bold\";")
        self.lblHoras.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHoras.setObjectName("lblHoras")
        self.lblTarifa = QtWidgets.QLabel(self.centralwidget)
        self.lblTarifa.setGeometry(QtCore.QRect(20, 70, 90, 41))
        self.lblTarifa.setStyleSheet("font: 13pt \"Gill Sans Ultra Bold\";")
        self.lblTarifa.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTarifa.setObjectName("lblTarifa")
        self.txtHoras = QtWidgets.QLineEdit(self.centralwidget)
        self.txtHoras.setGeometry(QtCore.QRect(130, 30, 113, 20))
        self.txtHoras.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtHoras.setObjectName("txtHoras")
        self.txtTarifa = QtWidgets.QLineEdit(self.centralwidget)
        self.txtTarifa.setGeometry(QtCore.QRect(130, 80, 113, 20))
        self.txtTarifa.setObjectName("txtTarifa")
        self.txtS = QtWidgets.QTextEdit(self.centralwidget)
        self.txtS.setGeometry(QtCore.QRect(29, 139, 301, 161))
        self.txtS.setObjectName("txtS")
        self.lblIcon = QtWidgets.QLabel(self.centralwidget)
        self.lblIcon.setGeometry(QtCore.QRect(350, 170, 131, 131))
        self.lblIcon.setText("")
        self.lblIcon.setPixmap(QtGui.QPixmap("c:\\Users\\PC-12\\Desktop\\EDDPOO_II.04.2023-IIE\\SEMANA5\\trabajo.png"))
        self.lblIcon.setScaledContents(True)
        self.lblIcon.setObjectName("lblIcon")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txtHoras, self.txtTarifa)
        MainWindow.setTabOrder(self.txtTarifa, self.btnProcesar)
        MainWindow.setTabOrder(self.btnProcesar, self.btnLimpiar)
        MainWindow.setTabOrder(self.btnLimpiar, self.btnSalir)
        MainWindow.setTabOrder(self.btnSalir, self.txtS)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnProcesar.setText(_translate("MainWindow", "PROCESAR"))
        self.btnLimpiar.setText(_translate("MainWindow", "LIMPIAR"))
        self.btnSalir.setText(_translate("MainWindow", "SALIR"))
        self.lblHoras.setText(_translate("MainWindow", "Horas :"))
        self.lblTarifa.setText(_translate("MainWindow", "Tarifa :"))
